-- 1. PREREQUISITE TASK

DROP TABLE labs.person

CREATE TABLE IF NOT EXISTS labs.person (
id integer NOT NULL,
name varchar(15)
);

EXPLAIN ANALYZE
INSERT INTO labs.person VALUES
(1, 'Bob'),
(2, 'Alice'),
(3, 'Robert');



-- 2. TABLES

-- 2.1 TASK 1 – PERFOMANCE WITH UNLLOGED TABLES

CREATE TABLE IF NOT EXISTS labs.test_simple(
a INT, 
b INT
);

INSERT INTO  labs.test_simple VALUES 
(generate_series(1,1000000));

INSERT INTO  labs.test_simple VALUES 
(generate_series(1,5000000));



CREATE UNLOGGED TABLE IF  NOT EXISTS labs.test_unlogged(
a INT,
b INT);

INSERT INTO  labs.test_unlogged VALUES 
(generate_series(1,1000000));




INSERT INTO  labs.test_unlogged VALUES 
(generate_series(1,5000000));



-- TASK 2 – UNDERSTANDING INHERITED TABLES

CREATE TABLE labs.users(
user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
login VARCHAR(30)) 
INHERITS (labs.person);


INSERT INTO labs.users (id, name,login)VALUES
(1, 'new Bob', 'NewLogin'),
(999, 'TestUser', 'TestLogin');

SELECT * FROM labs.users;
SELECT * FROM labs.person;
SELECT * FROM ONLY labs.person;



UPDATE labs.person
SET name = 'not Bob'
WHERE id = 1;

SELECT * FROM labs.users;



UPDATE ONLY labs.person
SET name = 'new Bob'
WHERE id = 1;


SELECT * FROM labs.users;

SELECT * FROM labs.person;




ALTER TABLE labs.person ADD COLUMN status integer DEFAULT 0;
ALTER TABLE labs.person ADD CONSTRAINT status CHECK (status in (0,1)) NO
INHERIT;
ALTER TABLE labs.person ADD CONSTRAINT id UNIQUE (id, name);



SELECT * FROM labs.person;

SELECT * FROM labs.users;


--3. INDEXES

-- 3.1 TASK 3 - BRIN VS B-TREE

CREATE TABLE IF NOT EXISTS labs.test_index (
num float NOT NULL,
load_date timestamptz NOT NULL
);

INSERT INTO labs.test_index(num, load_date)
SELECT random(), x
FROM generate_series('2017-01-01 0:00'::timestamptz,
'2021-12-31 23:59:59'::timestamptz, '10 seconds'::interval) x;

SELECT pg_size_pretty(pg_relation_size('labs.test_index'));



SELECT date_trunc('year', load_date), max(num)
FROM labs.test_index
WHERE load_date BETWEEN '2021-09-01 0:00' AND '2021-10-31 11:59:59'
GROUP BY 1
ORDER BY 1;


























	

